server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_SERVER}:${DATABASE_PORT}/${DATABASE_NAME}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    cors:
      allowed-origins: ${CLIENT_HOST}
jwt:
  signerKey: ${SIGNERKEY}

