server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_SERVER}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update #validate #none #
    show-sql: true
  graphql:
    cors:
      allowed-origins: ${CLIENT_HOST}
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true
    enabled: true
    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI:http://localhost:3000/oauth2/redirect}
            user-info-uri: ${USER_INFO_URI:https://www.googleapis.com/oauth2/v1/userinfo}
jwt:
  signerKey: ${SIGNERKEY}

